import { Router } from "express";
import { authRouter } from "../modules/auth/auth.routes";
import { activitiesRouter } from "../modules/activities/activities.routes";
import { agendaEventsRouter } from "../modules/agenda-events/agenda-events.routes";
import { clientsRouter } from "../modules/clients/clients.routes";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes";
import { evidencesRouter } from "../modules/evidences/evidences.routes";
import { inventoryRouter } from "../modules/inventory/inventory.routes";
import { invoicesRouter } from "../modules/invoices/invoices.routes";
import { materialRequestsRouter } from "../modules/material-requests/material-requests.routes";
import { paymentsRouter } from "../modules/payments/payments.routes";
import { permissionsRouter } from "../modules/permissions/permissions.routes";
import { projectsRouter } from "../modules/projects/projects.routes";
import { pushRouter } from "../modules/push/push.routes";
import { settingsRouter } from "../modules/settings/settings.routes";
import { timeEntriesRouter } from "../modules/time-entries/time-entries.routes";
import { toolAssignmentsRouter } from "../modules/tool-assignments/tool-assignments.routes";
import { toolIncidentReportsRouter } from "../modules/tool-incident-reports/tool-incident-reports.routes";
import { usersRouter } from "../modules/users/users.routes";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/projects", projectsRouter);
apiRouter.use("/clients", clientsRouter);
apiRouter.use("/activities", activitiesRouter);
apiRouter.use("/evidences", evidencesRouter);
apiRouter.use("/invoices", invoicesRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/time-entries", timeEntriesRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/push", pushRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/material-requests", materialRequestsRouter);
apiRouter.use("/tool-assignments", toolAssignmentsRouter);
apiRouter.use("/tool-incident-reports", toolIncidentReportsRouter);
apiRouter.use("/agenda-events", agendaEventsRouter);
apiRouter.use("/permissions", permissionsRouter);
