/**
 * Códigos de error estables usados por ApiError y consumidos por el cliente
 * para mapear a claves de traducción (es/en/pap). El mensaje en español que
 * viaja junto al código es solo fallback/log interno, no para mostrar tal cual
 * en la UI.
 */
export const ErrorCode = {
  // Genéricos / middleware
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UPLOAD_ERROR: "UPLOAD_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",

  // Auth
  MISSING_TOKEN: "MISSING_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN_ROLE: "FORBIDDEN_ROLE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_SESSION: "INVALID_SESSION",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  USER_ACCOUNT_DEACTIVATED: "USER_ACCOUNT_DEACTIVATED",
  USER_ALREADY_INACTIVE: "USER_ALREADY_INACTIVE",
  USER_ALREADY_ACTIVE: "USER_ALREADY_ACTIVE",
  CANNOT_DEACTIVATE_SELF: "CANNOT_DEACTIVATE_SELF",
  WORKER_DOCUMENT_NOT_FOUND: "WORKER_DOCUMENT_NOT_FOUND",
  WORKER_DOCUMENT_DELETE_FORBIDDEN: "WORKER_DOCUMENT_DELETE_FORBIDDEN",

  // Proyectos
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_HAS_ACTIVITIES: "PROJECT_HAS_ACTIVITIES",

  // Clientes
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  CLIENT_HAS_PROJECTS: "CLIENT_HAS_PROJECTS",

  // Pagos
  PROJECT_HAS_NO_CLIENT: "PROJECT_HAS_NO_CLIENT",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",

  // Actividades
  ACTIVITY_NOT_FOUND: "ACTIVITY_NOT_FOUND",
  ACTIVITY_NOT_ASSIGNED: "ACTIVITY_NOT_ASSIGNED",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  ACTIVITY_MISSING_APPROVED_EVIDENCE: "ACTIVITY_MISSING_APPROVED_EVIDENCE",
  ALREADY_ASSIGNED: "ALREADY_ASSIGNED",
  ASSIGNMENT_NOT_FOUND: "ASSIGNMENT_NOT_FOUND",
  USER_NOT_FIELD_WORKER: "USER_NOT_FIELD_WORKER",

  // Evidencias
  EVIDENCE_NOT_FOUND: "EVIDENCE_NOT_FOUND",
  EVIDENCE_DELETE_FORBIDDEN: "EVIDENCE_DELETE_FORBIDDEN",
  UNSUPPORTED_IMAGE_TYPE: "UNSUPPORTED_IMAGE_TYPE",
  IMAGE_REQUIRED: "IMAGE_REQUIRED",

  // Marcación de horas
  OPEN_ENTRY_EXISTS: "OPEN_ENTRY_EXISTS",
  NO_OPEN_ENTRY: "NO_OPEN_ENTRY",
  TIME_ENTRY_NOT_FOUND: "TIME_ENTRY_NOT_FOUND",
  ALREADY_ON_LUNCH: "ALREADY_ON_LUNCH",
  NO_OPEN_LUNCH: "NO_OPEN_LUNCH",
  NO_OPEN_ENTRY_FOR_LUNCH: "NO_OPEN_ENTRY_FOR_LUNCH",
  CANNOT_EXIT_DURING_LUNCH: "CANNOT_EXIT_DURING_LUNCH",

  // Facturas
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVALID_INVOICE_TRANSITION: "INVALID_INVOICE_TRANSITION",
  RETURN_COMMENT_REQUIRED: "RETURN_COMMENT_REQUIRED",
  FILE_REQUIRED: "FILE_REQUIRED",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",

  // Inventario
  INVENTORY_ITEM_NOT_FOUND: "INVENTORY_ITEM_NOT_FOUND",
  INVENTORY_ITEM_HAS_ACTIVE_ASSIGNMENTS: "INVENTORY_ITEM_HAS_ACTIVE_ASSIGNMENTS",
  INVENTORY_ITEM_HAS_PENDING_REQUESTS: "INVENTORY_ITEM_HAS_PENDING_REQUESTS",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",

  // Solicitudes de materiales
  MATERIAL_REQUEST_NOT_FOUND: "MATERIAL_REQUEST_NOT_FOUND",
  INVALID_MATERIAL_REQUEST_TRANSITION: "INVALID_MATERIAL_REQUEST_TRANSITION",
  MATERIAL_REQUEST_ITEM_REQUIRED: "MATERIAL_REQUEST_ITEM_REQUIRED",

  // Herramientas asignadas
  TOOL_ASSIGNMENT_NOT_FOUND: "TOOL_ASSIGNMENT_NOT_FOUND",
  TOOL_ASSIGNMENT_ALREADY_RETURNED: "TOOL_ASSIGNMENT_ALREADY_RETURNED",
  ITEM_NOT_A_TOOL: "ITEM_NOT_A_TOOL",

  // Reportes de daño/pérdida
  TOOL_INCIDENT_REPORT_NOT_FOUND: "TOOL_INCIDENT_REPORT_NOT_FOUND",
  TOOL_INCIDENT_ALREADY_RESOLVED: "TOOL_INCIDENT_ALREADY_RESOLVED",
  TOOL_NOT_ASSIGNED_TO_YOU: "TOOL_NOT_ASSIGNED_TO_YOU",

  // Agenda
  AGENDA_EVENT_NOT_FOUND: "AGENDA_EVENT_NOT_FOUND",
  AGENDA_EVENT_EDIT_FORBIDDEN: "AGENDA_EVENT_EDIT_FORBIDDEN",
  AGENDA_EVENT_END_BEFORE_START: "AGENDA_EVENT_END_BEFORE_START",

  // Acceso por seccion (Feature)
  FEATURE_ACCESS_DENIED: "FEATURE_ACCESS_DENIED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
