/**
 * Códigos de error estables usados por ApiError y consumidos por el cliente
 * para mapear a claves de traducción (es/en/pap). El mensaje en español que
 * viaja junto al código es solo fallback/log interno, no para mostrar tal cual
 * en la UI.
 */
export const ErrorCode = {
  // Genéricos / middleware
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UPLOAD_ERROR: "UPLOAD_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",

  // Auth
  MISSING_TOKEN: "MISSING_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN_ROLE: "FORBIDDEN_ROLE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_SESSION: "INVALID_SESSION",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_TAKEN: "EMAIL_TAKEN",

  // Proyectos
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_HAS_ACTIVITIES: "PROJECT_HAS_ACTIVITIES",

  // Actividades
  ACTIVITY_NOT_FOUND: "ACTIVITY_NOT_FOUND",
  ACTIVITY_NOT_ASSIGNED: "ACTIVITY_NOT_ASSIGNED",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  ALREADY_ASSIGNED: "ALREADY_ASSIGNED",
  ASSIGNMENT_NOT_FOUND: "ASSIGNMENT_NOT_FOUND",
  USER_NOT_FIELD_WORKER: "USER_NOT_FIELD_WORKER",

  // Evidencias
  EVIDENCE_NOT_FOUND: "EVIDENCE_NOT_FOUND",
  EVIDENCE_DELETE_FORBIDDEN: "EVIDENCE_DELETE_FORBIDDEN",
  UNSUPPORTED_IMAGE_TYPE: "UNSUPPORTED_IMAGE_TYPE",
  IMAGE_REQUIRED: "IMAGE_REQUIRED",

  // Marcación de horas
  OPEN_ENTRY_EXISTS: "OPEN_ENTRY_EXISTS",
  NO_OPEN_ENTRY: "NO_OPEN_ENTRY",
  TIME_ENTRY_NOT_FOUND: "TIME_ENTRY_NOT_FOUND",

  // Facturas
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVALID_INVOICE_TRANSITION: "INVALID_INVOICE_TRANSITION",
  RETURN_COMMENT_REQUIRED: "RETURN_COMMENT_REQUIRED",
  FILE_REQUIRED: "FILE_REQUIRED",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
